name: PR
on:
  pull_request:
  push:
    branches: [ main, no-cdt ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    strategy:
      matrix:
        python-version: [3.9]
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev
          sudo apt-get install ninja-build
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 14
          platform: x64
      - name: show clang version
        run: |
          clang --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
      - name: Install cdt
        run: |
          python3 -m pip install -U eoscdt
          eoscdt check
      - name: Install EOS test framework
        run: |
          python3 -m pip install ipyeos
      - name: Run eosdebugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eosdebugger &
      - name: build
        run: |
          mkdir build
          cd build
          CXX=clang++ CC=clang cmake -DENABLE_COVERAGE=TRUE -DBUILD_TESTS=TRUE -DCMAKE_BUILD_TYPE=Debug -Dcdt_DIR=`cdt-get-dir` -GNinja ..
          ninja
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: test
        working-directory: build
        run: |
          ./tests/tests
      - name: test coverage
        working-directory: build
        run: |
          export TEST_COVERAGE=1
          ./tests/tests
      - name: upload coverage file to codecov
        run: |
          cd build
          /usr/lib/llvm-14/bin/llvm-cov gcov `find . -name "*.gcda"`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
