name: PR
on:
  pull_request:
  push:
    branches: [ main, no-cdt ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    strategy:
      matrix:
        python-version: [3.9]
        step: ['test']
        # step: ['lint', 'test:chain']
    name: ${{ matrix.step }}
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 7
          platform: x64
      - name: show clang version
        run: |
          clang --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
      - name: Install cdt
        run: |
          wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.7.0/eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb
          sudo apt install ./eosio.cdt_1.7.0-1-ubuntu-18.04_amd64.deb
      - name: Install boost
        run: |
          sudo apt-get install libboost-all-dev
      - name: Install llvm
        run: |
          sudo apt install llvm
      - name: Install EOS test framework
        run: |
          python3 -m pip install ipyeos
      - name: Run eos-debugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eos-debugger &
      - name: build
        run: |
          mkdir build
          cd build
          CXX=clang++ CC=clang cmake -DENABLE_COVERAGE=TRUE -DBUILD_TESTS=TRUE -DCMAKE_BUILD_TYPE=Debug ..
          make -j4
      - name: test
        run: |
          cd build
          ./tests/tests
          find . -name "*.gcno"
          curl -S -f https://codecov.io/bash -o codecov
          chmod +x codecov
          ./codecov -x "llvm-cov gcov" -Z
